### PR TITLE
Iio als filters

### LINKED ISSUE #394: Droid4: mce should light up the android button backlight wen apropriate.

### PR DESCRIPTION
**Pull request by IMbackK**
Commit after iio-als

adds new modules that use iio-als for display brighness and key backlights
replaces keypad.c with a more configurable button-backlight.c fixes https://github.com/maemo-leste/bugtracker/issues/394

Limitations:
* iio-sensor-proxy filters light sensor data, but the filter is mutch faster than mces, i dont know if i like this
  * mce cant just use a moving window filter like it did with the old implmentation because iio-sensor-proxy only provides als changes
  * mce might need another type of filter in iio-als.c (id rather implement this as a datapipe filterm not in this module)
* button-backlight.c dosent provide fading support atm (WIP)
  * ~~note that on devices with hardware fading the fading will work regardless~~ (depends)
* ~~button-backlight.c dosent provide the timeout (dosent work in current code either, need discussion)~~

### CODE REVIEW

**Comment by IMbackK** [comment]
after using it a while i think i like the speed of the als filter in iio_sensor_proxy

**Comment by IMbackK** [comment]
To do: add all the lights/ policy from the other devices we support to mce.ini for button-backlight.c
can someone who owns them help me with this? (button-backlight.c just ignores ones that dont exist)
or make mce.ini a device specfic file in leste-config (id prefer this).

~~note both are temporary solutions, long term i think its best to split mce.ini into mce.ini and mce-device.ini or something like that.~~
pr18 fixes this

note that these modules are not used by default and without a file equivalent to https://github.com/maemo-leste/leste-config/pull/5/files, the old modules are used instead. sutch a file remains to be written for n900 and pp.

**Comment by IMbackK** [comment]
regarding: button-backlight.c dosent provide the timeout (dosent work in current code either, need discussion)
I will not "fix" this. The current behaviour of this is superior to the original code. Explanation of behaviour:

Old code:

1. screen turns on due to keyboard opened up
  - keyboard backlight turns on
  - hard coded 30 sec timeout starts in keypad.c
  - user set display dim timeout starts (10 sec - 120 sec)
2. Possibly: keypad.c timeout times out
  - keypad backlight turns off
  - might also happen after 3 or never depending on user settings
3. display dims
  - display is set to lowest brightness
  - gconf controlled display off timeout starts
4. display turns off
  - might also turn of keypad backlight if the total dispaly timeout is < 30 sec

This pr:

1. screen turns on due to keyboard opened up
  - all configured button backlights turn on
  - user set display dim timeout starts (10 sec - 120 sec)
2. display dims
  - some button backlights turn off (which ones is controlled in mce.ini)
  - display is set to lowest brightness
  - gconf controlled display off timeout starts
3. display turns off
  - button backlights not turned off in 2 now turn off

**Comment by MerlijnWajer** [comment]
Merged, but please make following changes:

16:51 < Wizzup> I merged this, but please don't do inline if statements like this:
                https://github.com/maemo-leste/mce/pull/15/files#diff-f65557e9f5bccb6b47ab1d25207ad2c9R272

**Pull request closed without merging**
