### PR TITLE
Move to new build system: cmake

### PR DESCRIPTION
**Pull request by IMbackK**

### CODE REVIEW

**Comment by parazyd** [comment]
utACK

**Comment by IMbackK** [comment]
also remove https://github.com/maemo-leste/mce-dev from jenkins when this dropps

**Comment by MerlijnWajer** [comment]
@parazyd can you remove `mce-dev` from -devel jenkins? Then we can build this, and once it's ok, maybe deprecate/archive the repo?

We'll want to do it in two steps though, not to break non-devel

**Comment by parazyd** [comment]
mce-dev is not in devel, only in stable.
The actual jenkins job doesn't matter and can be removed whenever.

**Comment by IMbackK** [comment]
please keep the the mce-dev repo around for now
i still need to pick the doxygen stuff from it

**Pull request merged**
