### PR TITLE
mce-hal: remove. no longer nessecary.

### PR DESCRIPTION
**Pull request by IMbackK**
Instead of hard coded device configuration, mce.ini.d configuration is now used

some old modules that only support n900 and older where striped down to be n900 only and are now device specific modules
changed where:

led:     removed support for <n900 changed to device specific module
keypad:  removed support for <n900, ~~droid4 compability also retained.~~
         module also obsoleted by button-backlight.
homekey: this module just used mce-hal to deactivate itself if it ran on n900.
         now it allways runs, instead it is to be disabled in the device specific config file.
evdevvibrator: included mce-hal by mistake.

### CODE REVIEW

**Comment by IMbackK** [comment]
dont merge for now, merge the other stuff first, then let me rebase this on top of that

**Comment by IMbackK** [comment]
Let me explain what this prs purpose it in detail. First lets examine the way things currently work in mce:

1. mce-hal uses /proc/cpuinfo to determine what device it is running on based on a hard coded match list.
2. several modules use this information to change the way they behaive.
   * keypad.c chooses from a list of hardcoded sysfs paths to the keypad backlight.
   * display.c chooses from a list of hardcoded sysfs paths to the display backlight and enables/disables cabc.
   * led.c chooses has a totaly seperate code path for eatch supported device.
   * filter-brighness-als.c chooses from a list of hardcoded sysfs paths to the als.
   * and so on...

This design is of course deficient, because we want mce to work on any random device without needing to hard code a code path and sysfs paths for eatch one. To facilitate this i have been writing a suite of new modules, these new modules come in 3 types.

1. Fully generic modules
   * these are expected to work on any device without any device specific configureation 
2. Generic modules that require device specific configuration
   * a device specific config file in mce.ini.d is expected to provide the module with the information it needs
3. device specific modules
   * these modules contain device specific code paths to enable device specific features that are impractical to implement in a type 2 module
   * these modules are expected to not be loaded by default but by a device specific config file in  mce.ini.d

The benefit of this is obvious, a user can install mce on any random device, and by writing a device specific config file he can make mce support his device at minimal effort and without needing to fork/ recompile mce. If any device we support has the same eg. led chip as the users device he can also load the same type 3 module to get additional functionality.

Finally some examples of this change in action:

the type 2 module button-backlight.c replaces keypad.c:

old:
* keypad.c uses mce-hal to choose from a list of hardcoded sysfs paths to the keypad backlight.
* keypad.c uses mce-hal to choose from a list of policies of when to enable the light.

new:
* button-backlight.c uses the device specific config file in mce.ini.d to detimine what sysfs path to use
* button-backlight.c uses the device specific config file in mce.ini.d to detimine what policy to use for eatch backlight

led.c is split into led-dbus.c and various type 3 led-* hardware modules

old:
* led.c chooses has a totaly seperate code path for eatch supported device based on mce.hal

new:
* led-dbus is a type 1 model that provides the external interface to the led.
* the led-* family of modules are type 3 modules that are loaded based on the device specific config file in mce.ini.d and provide a backend to the relevant hardware.

Where dose this pr fit in?:

this pr is a cleanup operation. It removes mce-hal, and removes all the code paths in the legacy modules that pertain to devices other than the n900, these modules are now n900 specific type 3 modules that are to be loaded on n900 only via  the device specific config file in mce.ini.d.

This dose remove specific code for the n8xx and older devices, but:
- i dont see supporting devices with <=128 mb ram as something worthwhile for leste or a reason to carry a bunch of legacy code
- we dont know how mutch of the code still works on n8xx with reasonably modern linux anyways.
- If someone wants to use a n8xx with leste, this is still an option the n8xx can use the generic code paths with only minor degradation in features, these are:
  - no cabc support
  - led-sw needs to be used, causing a minor hit in battery life when a notification is enabled.

**Comment by IMbackK** [comment]
rebase done

**Comment by IMbackK** [comment]
note that keypad.c is not used by any device any more, so its changes are mostly irrelivant.

**Comment by IMbackK** [comment]
the previous auto rebase clobbered mce.ini ill fix that before merge/soon

**Comment by MerlijnWajer** [comment]
Merged to 1.8.128.24

**Pull request closed without merging**
