### PR TITLE
add iio-accelerometer

### PR DESCRIPTION
**Pull request by IMbackK**
legacy support module, intended only to be used by old applications to get orientation data. do not use in new applications

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Why is this not supposed to be used in new applications? Isn't it the maemo API that it implements?

**Comment by IMbackK** [comment]
This module provides the old maemo interface, yes. It dose this by duplicating the interface provided by iio-sensor-proxy. 

1. In stark contrast to the other iio* modules mce dose not use this information internally. 
2. This module is also unique in that it provides an external interface to a sensor
3. Any device where this module works has iio-sensor-proxy running

for these reasons i have deemed this module to _not_ be inside of the competencies of mce and therefore depeciated. Instead i expect new applications to use iio-sensor-proxy directly or use libiio or use, also legacy, iio-uinput to gain this information.

**Comment by clort81** [comment]
HI! where do I learn how to poll accelerometer?   Neverball wants eet! :D :D :dancers: 
cat /sys/devices/platform/44000000.ocp/48000000.interconnect/48000000.interconnect:segment@200000/48350000.target-module/48350000.i2c/i2c-3/3-0018/iio:device2/in_accel_x_raw 

 (also y and z) gets me changey numbers!

**Comment by IMbackK** [comment]
@clort81 Dont use this pr as a general discussion forum. 
Neverball with accelerometer input works fine using https://github.com/IMbackK/iio-uinput.

**Comment by clort81** [comment]
> @clort81 Dont use this pr as a general discussion forum.
OK

> Neverball with accelerometer input works fine using https://github.com/IMbackK/iio-uinput.

Can you post the changes to neverball Makefile & sources somewhere?  Thanks.

**Pull request merged**
